### ISSUE TITLE
Add Test suite for front-end codebase

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#10]
It is important to implement the TDD methodology to ensure that the code is thoroughly tested before being added to the repository. This involves conducting Unit Tests, E2E Testing, and Integration Testing at each stage.

Reference: [TDD Approach](https://www.browserstack.com/guide/what-is-test-driven-development#:~:text=Test%2Ddriven%20development%20(TDD)%20is%20a%20software%20development%20practice,and%20then%20refactoring%20the%20code.)

**Comment by Atrika10** [comment]
I would like to work on this issue. please assign this issue to me.

**Comment by Maghish** [comment]
Hey @Atrika10 , can I also collaborate with this issue?

**Comment by Atrika10** [comment]
To solve this we need to have a knowledge of **_Jest_** (Jest is a JavaScript testing framework designed to ensure the correctness of any JavaScript codebase.). It will take time to complete this issue.
currently, I'm unassigning myself from this issue.
If anyone is interested to work on this, you can take this issue.

Reference:  https://jestjs.io/docs/getting-started

Thanks

**Comment by SID262000** [comment]
Thanks @Atrika10 for sharing the required background knowledge for handling this Issue.
I would just like to mention, this is a great learning opportunity for anyone looking to broaden their front end Development knowledge base, as it includes the TDD approach for JS.

**Comment by Maghish** [comment]
Hey @SID262000, I started learning JS and Jest. But right now, I am not clear what to test. Like should I test the html element?
or just write a test?

**Comment by SID262000** [comment]
To the best of my knowledge, JEST is used to check the JS code, not really sure if it helps check HTML as well.
Action item would be to start with unit tests for each module(javascript code) and test it.

**Comment by Maghish** [comment]
But there is no javascript code here

**Comment by SID262000** [comment]
Strange!

**Comment by AryanGupta0007** [comment]
Would figure out a way to generate code coverage report for frontend .
Cc: @SID262000

**Comment by Maghish** [comment]
@SID262000 The Pull request has been merged. So we can close the issue now 
right?

**Comment by SID262000** [comment]
Yes, Thanks

**Comment by Maghish** [comment]
Successfully added the test suites for front-end codebase, now it's better to close this issue.
Cc: @SID262000
