### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#2]
Please ensure that you have a detailed README file that provides an overview of your project, including details on how to get started, setting up the initial setup, and how someone can collaborate if they are interested.

References:

- https://github.com/bloomberg/blazingmq

Resources:

- https://github.com/matiassingers/awesome-readme
- https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- https://coding-boot-camp.github.io/full-stack/github/professional-readme-guide

**Comment by Devansh-Singh-Parmar** [comment]
We kind of made it

**Comment by SID262000** [comment]
I would suggest keeping the Issue open for further scope of improvisation on the existing one.
cc: @Devansh-Singh-Parmar

**Comment by SID262000** [comment]
Don't close any issues by yourself. It's always recommended that the maintainer/person creating the issue closes it.
Also I see a lot of missing pieces to the README which we need to discuss and get sorted.

**Comment by N3v1** [comment]
Hi @SID262000 👋,
I found some formatting errors in the README.md. The terminal commands are not formatted under the item 'Getting Started'.

## **How ​​to fix the error?**
Put the terminal commands between `` or ```bash.

## **Example:**
Clone the repository:
`git clone https://github.com/TeamCodeArena/DeliverEase`

---

If it's okay with you, I could do it

Best regards
NH

**Comment by N3v1** [comment]
Hi @SID262000 👋,
Hi @Devansh-Singh-Parmar 👋,
I would recommend moving the contribute text to the Contribute.md file.
This would improve the readability of the README.md

Best regards
NH

**Comment by SID262000** [comment]
Agreed, @N3v1
Can you please work with @Devansh-Singh-Parmar to fix it ASAP, Many Thanks

**Comment by N3v1** [comment]
Also, I suggest that the Readme.md be redesigned only if you are comfortable with it. If you give me permission, I would be happy to handle the task.

Thank you kindly 🙏
Best regards
NH

**Comment by N3v1** [comment]
Okay @SID262000 
Thank you

**Comment by SID262000** [comment]
@N3v1 Definitely it requires a lot of additional changes such as including the testcase running commands, including information on linters used, and many more. I would really appreciate your effort here. Please keep me in loop while making any changes or additions.
cc: @Devansh-Singh-Parmar

**Comment by SID262000** [comment]
Consider adding a link to our Slack community as well in the README for enhanced communication and collaboration.
cc: @Devansh-Singh-Parmar @N3v1

**Comment by N3v1** [comment]
Okay @SID262000, Sure, I can help you with that. Kindly provide me with the link to your Slack community and I will add it to the readme.md.

**Comment by SID262000** [comment]
Here you go!
Slack Community [Link](https://join.slack.com/t/deliverease-group/shared_invite/zt-20dy1cqu9-A08Lpx3p7F7advXQWPedFQ)
@N3v1 Please feel free to join the community, I highly encourage and would really appreciate it!
Note: Above link expires in next **24 Days**

**Comment by N3v1** [comment]
Hi @SID262000 👋,
Can you give me a link that can't expire so that I can implement it in the Readme.md

**Comment by SID262000** [comment]
@N3v1 I don't think it exists. Feel free to research on it and pass on any leads if found, Thanks

**Comment by N3v1** [comment]
@SID262000  I just created a PR with the new Redme.md. I'm not quite done yet, I only have to link files, but I don't know if they already exist because others are linked to the task.

Best regards
NH

**Comment by SID262000** [comment]
@Devansh-Singh-Parmar Please work with @N3v1 to get this issue resolved at the earliest, Thanks

**Comment by N3v1** [comment]
Hi @SID262000 👋,
Would it be possible for you to create a directory called "only-for-documentation" where you could leave me some screenshots of the app?

Thank you kindly 🙏
Best regards
NH

**Comment by SID262000** [comment]
We haven't released the product in the form of app or website yet, so it would be difficult to capture any snapshots at the moment.
cc: @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
Correct @SID262000 , and @N3v1  please remove the contribution part from Readme, I am already working on the new Contributor.md

**Comment by SID262000** [comment]
@Devansh-Singh-Parmar Do you see any conflicts with your existing contribution.
cc: @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
@SID262000 I didn't got you, what do you mean?

**Comment by Devansh-Singh-Parmar** [comment]
@N3v1  here you go, this [link](https://join.slack.com/t/deliverease-group/shared_invite/zt-20af47vjo-msHq~8~PRsmi3x5~rMzs7g) never expires

**Comment by SID262000** [comment]
Since you requested @N3v1 to remove his part of Contribution.md related changes, was it for a specific reason as such because going back is something I wouldn't encourage following until there's a solid reason behind that.

**Comment by N3v1** [comment]
> We haven't released the product in the form of app or website yet, so it would be difficult to capture any snapshots at the moment. cc: @N3v1

Okay

**Comment by N3v1** [comment]
> 

Thank you @Devansh-Singh-Parmar 🙏

**Comment by Devansh-Singh-Parmar** [comment]
@SID262000 Already making Contributor.md, what's need of the instructions in Readme?

**Comment by SID262000** [comment]
@Devansh-Singh-Parmar README is the main landing and visible section for our customers and future contributors, where they get their very first impression!
It's important to link Contributing from README for easy accessibility of Contribution guidelines for future Contributors.
cc: @N3v1

**Comment by N3v1** [comment]
Hello @SID262000 ,
@Devansh-Singh-Parmar is correct, but to be on the safe side, let's not leave the contribution steps in until his PR has been accepted.

**Comment by N3v1** [comment]
After his PR is accepted, I can replace the Contribute section with a link to the Contribute.md

**Comment by SID262000** [comment]
Yes, @N3v1 
We need to get the Contribution file in place before linking it from elsewhere.
cc: @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
Doing that now 
cc: @SID262000

**Comment by SID262000** [comment]
Great work @Devansh-Singh-Parmar and @N3v1 for putting a great first read from the README file. This will really help new comers to explore the product from all perspectives.
