### ISSUE TITLE
Create Milestones for MVP

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#24]
Reference LInks:

- [Milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones)
- [Best Practices](https://learn.microsoft.com/en-us/contribute/dotnet/labels-projects#:~:text=We%20use%20GitHub%20projects%20to,for%20work%20(pull%20requests).)

**Comment by Devansh-Singh-Parmar** [comment]
I would love to help!
cc: @SID262000

**Comment by SID262000** [comment]
Sure @Devansh-Singh-Parmar, let's take this up during our weekly staff meeting scheduled at 10pm IST on Saturday

**Comment by Devansh-Singh-Parmar** [comment]
@SID262000 Please create some milestones

**Comment by SID262000** [comment]
@Devansh-Singh-Parmar It can't be created unless we enter the development phase

**Comment by Devansh-Singh-Parmar** [comment]
Okay it's about that, great!
@SID262000

**Comment by SID262000** [comment]
I've added 4 Milestones for the upcoming Release of our software which we need to track down really closely. Thanks!
cc: @AryanGupta0007 @Devansh-Singh-Parmar
