### ISSUE TITLE
Add Labels to each Issue for enhanced clarity

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#3]
As I'm not the owner of the repo, looks like I don't have the flexibility to attach any label to the issues. Please proceed with attaching a label against each issue as appropriate.

Reference:
- https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels

**Comment by Devansh-Singh-Parmar** [comment]
I already did that! please assign I'll create some more!

**Comment by SID262000** [comment]
I've taken care of this issue for now. Going forward, please consider this step as an integral part while creating any Issues.
