### ISSUE TITLE
Add Keyword labels to the README

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#32]
Reference Article: https://shields.io/

**Comment by Shashank7001** [comment]
Assign this issue to me.

**Comment by N3v1** [comment]
Maybe I can help you if you want @Shashank7001. Can't work on it until Friday though

Best regards 
NH

**Comment by KartikKar19** [comment]
@SID262000 If I don't need to add anything in the index.html then I can make a pull request and then work on another issue

**Comment by KartikKar19** [comment]
@SID262000 Kindly assign this issue to me.

**Comment by KartikKar19** [comment]
@SID262000 Kindly tell me in which parts you need keyword labels I will update the README accordingly.

**Comment by SID262000** [comment]
If you refer to the link attached as reference, those shields usually appear at top of the README
cc: @KartikKar19

**Comment by AryanGupta0007** [comment]
Any updates on the issue @KartikKar19 . Do you need any help?

**Comment by KartikKar19** [comment]
@AryanGupta0007 yeah I am currently working on it locally but the issue is I am just adding keywords on things I think are important.I don't know where to add keywords.Kindly guide me.

**Comment by AryanGupta0007** [comment]
Cc:@SID262000 please guide @KartikKar19 on what labels are required.

**Comment by AryanGupta0007** [comment]
@KartikKar19 one label that u can add on top is code coverage

**Comment by KartikKar19** [comment]
@AryanGupta0007 okay thanks I will add that.

**Comment by KartikKar19** [comment]
@SID262000 just tell me which ones we need to add I will add it accordingly and finish this by tomorrow.

**Comment by SID262000** [comment]
@KartikKar19 Please add the most appropriate ones from the list below.

https://github.com/alexandresanlim/Badges4-README.md-Profile

cc: @AryanGupta0007

**Comment by KartikKar19** [comment]
@SID262000 @AryanGupta0007 Kindly see my forked repo. I have added some keyword labels and badges which are interactive and some static . Tell me if you want any changes.

**Comment by N3v1** [comment]
Hi @KartikKar19,
Thanks for your work but I think that you used too many labels. I'd recommend you to look at [**this**](https://github.com/CodeEditApp/CodeEdit) repo to see how the labels can be used efficiently. 

Repo: https://github.com/CodeEditApp/CodeEdit

cc: @SID262000

**Comment by KartikKar19** [comment]
@N3v1 Thanks, I will make the changes accordingly and let you guys know.

**Comment by SID262000** [comment]
Many Thanks @KartikKar19 @N3v1 for your collaboration. Looking forward to seeing more progress on this front.

**Comment by SID262000** [comment]
Feel free to close this Issue, if completed 
cc: @KartikKar19 @N3v1
