### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#33]
Reference Link: https://github.com/github/docs/blob/main/CONTRIBUTING.md

**Comment by Devansh-Singh-Parmar** [comment]
please assign this

**Comment by AryanGupta0007** [comment]
Can i also work on this issue and submit a PR which includes  all the git commands as well as instructions given to me by you about how to contribute and avoid merge conflicts. @SID262000

**Comment by Devansh-Singh-Parmar** [comment]
You can suggest in the ongoing pull request, i'll change
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar i saw that and noticed that there is a lot to change so i made a contribute.md of my own as that would be better instead of changing yours as that would be a greater challenge according to me.

**Comment by Devansh-Singh-Parmar** [comment]
As you wish @AryanGupta0007

**Comment by SID262000** [comment]
I see too many people working on this Issue. Please compare the differences very consciously and make sure only one PR is created for this Issue with one single commit involved, Thanks
cc: @Devansh-Singh-Parmar @AryanGupta0007 @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
Will create a different pr once everything is solved
cc: @SID262000

**Comment by AryanGupta0007** [comment]
@SID262000 now that PR is merged, we should close this issue?

**Comment by SID262000** [comment]
Yes.
cc: @AryanGupta0007 @N3v1
