### ISSUE TITLE
Add Project Section

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#34]
Reference: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards

**Comment by N3v1** [comment]
Hi @SID262000, I can help you if you want

Best regards
NH

**Comment by N3v1** [comment]
Note: I will not be available until Friday 11am CET

**Comment by SID262000** [comment]
Thanks a lot, @N3v1 for extending the offer. I really appreciate it.
Sure thing, we can work together on this Issue on coming Friday 11th Aug

**Comment by AryanGupta0007** [comment]
Cc:@SID262000

**Comment by SID262000** [comment]
@N3v1 I'm waiting for your availability to work alongside me on this Issue. Do update ASAP, Thanks
cc: @AryanGupta0007

**Comment by N3v1** [comment]
Hi @SID262000, it would be great if we could start in **three days** because I‘m very busy right now. Thanks for your understanding

Best regards
NH

**Comment by SID262000** [comment]
@N3v1 Sure thing. Ping me as soon as you are available, we can start then. Many Thanks for all your support

**Comment by Ashwani1330** [comment]
@SID262000 
I would like to work on this issue.
Thanks

**Comment by SID262000** [comment]
@Ashwani1330 Right now, we are waiting for @N3v1 so that we all 3 can get started on this Issue. Based on the communication from @N3v1 , I'm expecting that he should be back by tomorrow.

**Comment by N3v1** [comment]
Hi @SID262000, we can now start 
Thanks @Ashwani1330 for your help

cc: @SID262000, @Ashwani1330

**Comment by SID262000** [comment]
Sure thing, @N3v1 

Is it possible for you to come on a Gmeet or Zoom because this Issue is sort of an open ended and does require a lot of brainstorming. Let me know in case you're available for the same, Thanks
cc : @Ashwani1330

**Comment by N3v1** [comment]
Hi @SID262000 👋🏼, 
I'm sorry, but unfortunately it's not possible because my internet connection isn't the best and for other security reasons. I would suggest we communicate on **Slack**? Early 10 am CET/CET?

cc: @Ashwani1330

**Comment by SID262000** [comment]
Yeah sure we can connect over slack. I'm available now until 1pm IST. Post that I'll be available around 11pm IST. Let me know if any of these time slots works for you.
cc: @Ashwani1330

**Comment by N3v1** [comment]
Both times are a bit tight @SID262000, how about tomorrow in terms of times, otherwise 8 or 8:30 pm CET/MEZ would suit me. Just let me know if this time is okay. 8pm CET/MEZ should be 11:30 pm IST, if my calculations are right `8:00 + 3:30 = 11:30 pm IST`
cc: @Ashwani1330

**Comment by SID262000** [comment]
11:30pm would be too late for me, as I would be exhausted and left with no energy!
cc: @N3v1 @Ashwani1330

**Comment by SID262000** [comment]
@N3v1 & @Ashwani1330 Please start working on this Issue, Thanks

**Comment by N3v1** [comment]
@SID262000, @Ashwani1330 I’m available at 15:00pm CET, 18:30pm IST I think

**Comment by SID262000** [comment]
I look forward to the discussion @N3v1 at 6:30 pm IST over Slack Huddle, Thanks for all the contributions.
cc: @Ashwani1330

**Comment by Ashwani1330** [comment]
Sorry, but I won't be available at 06:30pm.
Will be free after 9:00pm.

**Comment by SID262000** [comment]
No worries, @Ashwani1330 I or @N3v1 shall keep this thread updated with all the discussions.

**Comment by Devansh-Singh-Parmar** [comment]
Please update
cc: @SID262000 @N3v1

**Comment by SID262000** [comment]
@Ashwani1330 is working on this.
cc: @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
Okay
cc @SID262000 @Ashwani1330

**Comment by N3v1** [comment]
Hi @SID262000, In order to work on this issue we need write access to create the wiki and make changes to it. We can only create a project on our forks

@Ashwani1330, What do you think? Have you already begun to work on it?

cc: @Devansh-Singh-Parmar

**Comment by SID262000** [comment]
@AryanGupta0007 Please grant the necessary permissions to @N3v1 so that he can get started with the issue, Thanks
cc: @Ashwani1330

**Comment by AryanGupta0007** [comment]
Ok @SID262000 will look into this tommorow.

**Comment by SID262000** [comment]
Thanks @AryanGupta0007

**Comment by AryanGupta0007** [comment]
@N3v1 what kind of permissions are needed?. I mean where do you need a write access to?

**Comment by Ashwani1330** [comment]
> Hi @SID262000, In order to work on this issue we need write access to create the wiki and make changes to it. We can only create a project on our forks
> 
> @Ashwani1330, What do you think? Have you already begun to work on it?
> 
> cc: @Devansh-Singh-Parmar 

Yes, you are right.

I have created a project on my forked repo and shared it with others.
But it can't be merged via pull request.

So, we need permission to do the changes regarding the project on the original repository.

**Comment by SID262000** [comment]
@AryanGupta0007 For granting access, Thanks

**Comment by AryanGupta0007** [comment]
@SID262000 i have added the project section to this repo as i was confused about what permissions are needed so instead i have just added the project myself.

**Comment by SID262000** [comment]
That's really great folks!
cc: @AryanGupta0007 @Ashwani1330 @Devansh-Singh-Parmar @N3v1
