### ISSUE TITLE
Generate Code Coverage Report

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#35]
Reference Link: https://about.codecov.io/language/python/

We use a CodeCov report to indicate the percentage of the codebase tested. The ideal score varies from project to project, but 70-90% is good.

**Comment by Maghish** [comment]
Please assign this issue to me I will do it!

**Comment by Maghish** [comment]
I need more brief explanation on this please.

**Comment by SID262000** [comment]
Sure thing, @Maghish 
Let me get back to you with more details shortly, Thanks

**Comment by Maghish** [comment]
I just got confused.. Since I am not aware Code Coverage with CodeCov yet.

**Comment by SID262000** [comment]
That's fine, @Maghish .
Everyone is learning here, Thanks

**Comment by Maghish** [comment]
Both Front-end and Back-end code coverage is done so it's better to close the issue!
Cc: @SID262000
