### ISSUE TITLE
Add License.md file

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#36]
It is always important to have a licensed project for smooth collaboration and distribution of the software legally.

Reference: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

https://www.linkedin.com/advice/1/how-do-open-source-licenses-benefit-software?utm_source=share&utm_medium=member_android&utm_campaign=share_via

https://choosealicense.com/licenses/

**Comment by N3v1** [comment]
Hi @SID262000 👋,
I would like to help if it's okay with you

Thank you kindly 🙏
Best regards
NH

**Comment by SID262000** [comment]
Hi @N3v1,
Sure you can proceed with this issue. Please correct your display name so that it's easier for us to recognise you, Thanks

**Comment by N3v1** [comment]
Thanks @SID262000, but what do you mean by "Please correct your display name so we can recognize you more easily"

**Comment by SID262000** [comment]
Please correct from N3v1 to a real actual recognisable name

**Comment by N3v1** [comment]
Hi @SID262000 👋,
I just did a PR where I created a LICENSE.md based on the MIT license.

Thank you kindly 🙏
Best regards
NH

**Comment by SID262000** [comment]
Hi @N3v1,
Since this is your very first issue on our codebase. I would like to invite you to our weekly progress check meeting that happens tonight IST. Please let me know in case you're available for the same, Thanks

**Comment by N3v1** [comment]
I'm sorry @SID262000, but I don't have time, if something should happen, you can reach me via the email on my Github profile. Link to my Github profile [**here**](https://github.com/N3v1).

**Comment by SID262000** [comment]
That's fine, @N3v1 . If possible can you please introduce yourself in brief in the discussion section of this repo to enhance collaboration from a team perspective, Thanks

**Comment by N3v1** [comment]
@SID262000, Could you please advise me on the appropriate place to introduce myself in the discussions?

Thank you kindly 🙏
Best regards
NH

**Comment by SID262000** [comment]
Sure thing, @N3v1 
Feel free to add it [here](https://github.com/orgs/TeamCodeArena/discussions)

**Comment by SID262000** [comment]
@N3v1 Can you please follow up on the Discussion section, so that I can consider it's done, Thanks

**Comment by AryanGupta0007** [comment]
I think this reference can be helpful https://snyk.io/learn/open-source-licenses/ 
Cc: @SID262000 @N3v1

**Comment by SID262000** [comment]
We'll initially go with MIT License due to its permissive nature, but we might end up using the 4-claused BSD License once the product has gained sufficient traction in the market place to avoid misuse of the software.
@N3v1 If you think the MIT License is already in place, feel free to close this issue, Thanks

**Comment by SID262000** [comment]
Cc: @N3v1 For review

**Comment by N3v1** [comment]
> Cc: @N3v1 For review

I confirm my support for the MIT license @SID262000. However, I'm sorry to say that I do not quite understand your inquiry. Could you please provide some additional details to help me better understand what you are asking for?

Thank you kindly 🙏
Best regards
NH

**Comment by SID262000** [comment]
For now we will be proceeding with MIT LICENSE.
Later once the community becomes bigger we migrate to BSD 4 clause license

**Comment by SID262000** [comment]
I hope you get it now, @N3v1

**Comment by N3v1** [comment]
Yes, I understand now
