### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by N3v1** [TeamCodeArena/DeliverEase#40]
Hi all 👋,
Hi @SID262000 👋,
I noticed that this repo doesn't have a CODE_OF_CONDUCT.md file. 
If you want I could create the file for you

Best regards
NH

**Comment by SID262000** [comment]
Many Thanks, @N3v1 for creating this issue. Feel free to work on this. This is really helpful!

**Comment by N3v1** [comment]
Hi @SID262000,
I have submitted a PR that includes the newly created CODE_OF_CONDUCT.md file.

**Comment by SID262000** [comment]
@N3v1 Please make sure to include issue no. while writing the commit message & even while creating a PR to have all the related changes per Issue in one place, Thanks
