### ISSUE TITLE
Setup Github pages

### ISSUE THREAD

**Issue by AryanGupta0007** [TeamCodeArena/DeliverEase#43]
reference: https://pages.github.com/

**Comment by AryanGupta0007** [comment]
@N3v1 would like to work on this issue as well. Thanks!
cc: @SID262000

**Comment by SID262000** [comment]
I would really appreciate working on this issue in collaboration with @N3v1 
Please confirm, @N3v1, Thanks

**Comment by N3v1** [comment]
Yes I can help if you want @SID262000

**Comment by SID262000** [comment]
Sure, That will be really helpful @N3v1

**Comment by AryanGupta0007** [comment]
is someone working on this or can i work on this issue to create the github pages  for the sphinx docs? @SID262000 @N3v1

**Comment by N3v1** [comment]
I don't know it. It seems nobody is working on it right now @AryanGupta0007

**Comment by N3v1** [comment]
If you need help let me know

**Comment by AryanGupta0007** [comment]
If no one is working kindly assign this issue to me @SID262000

**Comment by SID262000** [comment]
@AryanGupta0007 GitHub Pages have no relation with Sphinx documentation. It's a totally separate standalone website page for our project which is cross linked from the right nav from the codebase section.

**Comment by AryanGupta0007** [comment]
Ok @SID262000

**Comment by SID262000** [comment]
If you want to work you can proceed. But be a bit cautious and don't confuse yourself.

**Comment by AryanGupta0007** [comment]
But don't we want to host the docs pages @SID262000

**Comment by SID262000** [comment]
That's a complete different process. We don't host documentation rather we link it from a particular section.

**Comment by AryanGupta0007** [comment]
Ok @SID262000 Maybe i misunderstood the issue

**Comment by N3v1** [comment]
Hi @SID262000 @AryanGupta0007,
should I set up the page? If so, shall I share the repo with you?

**Comment by Ashwani1330** [comment]
@SID262000 
I would like to work on this issue.
Thanks!

**Comment by N3v1** [comment]
Me too, in you need any help just let me know

**Comment by Ashwani1330** [comment]
I would like to ask if the deployment of GitHub pages should be done in this way as I did on my forked repository ?

https://ashwani1330.github.io/DeliverEase/

Because it just copies read-me content to the website so, I am doubtful.

**Comment by AryanGupta0007** [comment]
@SID262000

**Comment by SID262000** [comment]
@Ashwani1330 it's basically cross linked from the right navigation of the codebase.
cc: @N3v1 @AryanGupta0007

**Comment by Ashwani1330** [comment]
> @Ashwani1330 it's basically cross linked from the right navigation of the codebase. cc: @N3v1 @AryanGupta0007

@SID262000 
Sorry, but I did not understand. Could you please elaborate more on what is to be done?

**Comment by SID262000** [comment]
Follow steps from the below attached resource.
https://pages.github.com/

cc: @Ashwani1330

**Comment by Ashwani1330** [comment]
Okay.

**Comment by KartikKar19** [comment]
@SID262000
I would like to work on this issue.

**Comment by KartikKar19** [comment]
@SID262000 
We need to rename the readme file as README.md and also make an index.html that directly is read by GitHub pages and directly entered into our site/app from the HTML file.

**Comment by SID262000** [comment]
Thanks @KartikKar19 for the background investigation.
Please work with @Devansh-Singh-Parmar to get the above requirements in-place. Thanks

**Comment by KartikKar19** [comment]
@SID262000 
Ok will do so

**Comment by Devansh-Singh-Parmar** [comment]
I can only help with Readme fiile, please refer to @AryanGupta0007 for a new index.html
cc: @SID262000 @KartikKar19

**Comment by AryanGupta0007** [comment]
Do you need any help
@KartikKar19

**Comment by N3v1** [comment]
Is someone working on this issue right now or should I set up the GitHub page with my fork of this repo?

**Comment by Ashwani1330** [comment]
@N3v1 
I will do it.
Thanks!

**Comment by KartikKar19** [comment]
Sorry, I was out of town and my car got broken. I will do the needed with the readme file I don't know how to attach the index.html file

**Comment by KartikKar19** [comment]
@N3v1 
Guide me with how to link index.html with the mainstream code since I have changed the readme.md to README.md in my forked repo and created a new index.html but don't know how to proceed.

**Comment by KartikKar19** [comment]
@AryanGupta0007 kindly guide me with the index.html should I leave it blank?

**Comment by N3v1** [comment]
I don't quite understand what you want @KartikKar19. Would you like to link the file?
For example, link to index.html in the readme 
```md
To visit our website click [here](index.html)
```
So by clicking on "here" will transfer you to the index.html or do you mean something else?

**Comment by KartikKar19** [comment]
@N3v1 I am telling that the GitHub pages first read the README file and then the index.html file so if we add a blank index.html file then it will open a blank page in the GitHub pages link. I am not telling you to link the index.html with readme but to link the index.html with the Python code.

**Comment by Ashwani1330** [comment]
@N3v1 
I would like to ask what do we intend to display on the page? Is it the DeliverEase platform that is built using django and python to be displayed or something else?

& if it is that, then how can we connect that python implementation to the index.html?

**Comment by N3v1** [comment]
I am unsure of what content to display on @Ashwani1330's page. @SID262000, could you please provide some guidance on what should be shown?

Best regards
NH

**Comment by KartikKar19** [comment]
@SID262000 If I can leave the index.html blank then I just have to make a pull request as I have made changes with the readme file in the forked repo.

**Comment by N3v1** [comment]
>> @N3v1 I am telling that the GitHub pages first read the README file and then the index.html file so if we add a blank index.html file then it will open a blank page in the GitHub pages link. I am not telling you to link the index.html with readme but to link the index.html with the Python code.

No, unfortunately, I don't know how to link Python code @KartikKar19, but maybe you could try it with something like that:
```HTML
<link rel="" href="">
```
>I never tried it so maybe @SID262000 or everyone else could help you with that

**Comment by N3v1** [comment]
Additionally @SID262000, it is not possible to use Github Pages for this project because it has been built using Django and Python, which are not supported by Github Pages as it only supports static websites. See [**here**](https://stackoverflow.com/questions/29880626/possible-to-host-a-django-site-on-github-pages).

Best regards
NH

**Comment by SID262000** [comment]
> Additionally @SID262000, it is not possible to use Github Pages for this project because it has been built using Django and Python, which are not supported by Github Pages as it only supports static websites. See [**here**](https://stackoverflow.com/questions/29880626/possible-to-host-a-django-site-on-github-pages).
> 
> Best regards NH

Thanks for pointing out this incompatibility issue, @N3v1. Looks like we have to wait until we have the other missing pieces in-place first related to the actual codebase which will ultimately help us decide/improvise on the tools used in this program.

**Comment by SID262000** [comment]
Since we have this compatibility issue for the GitHub pages with Django & Python, I request everyone to wait until further notice on the change of the tool stack which will only be possible after we integrate the missing pieces.
Many thanks @Ashwani1330 @KartikKar19 @N3v1 for brainstorming this issue, I highly appreciate the due diligence.
cc: @AryanGupta0007

**Comment by AryanGupta0007** [comment]
I don't have a idea about the Github Pages index.html initially I thought that u are talking about project's index.html
@KartikKar19

**Comment by SID262000** [comment]
I just cc you @AryanGupta0007 for keeping you in the loop. No inputs are required from your end at this moment. Thanks

**Comment by Devansh-Singh-Parmar** [comment]
A polite ask for updates.

cc @Ashwani1330 @KartikKar19 @N3v1

**Comment by N3v1** [comment]
> Since we have this compatibility issue for the GitHub pages with Django & Python, I request everyone to wait until further notice on the change of the tool stack which will only be possible after we integrate the missing pieces.
> Many thanks @Ashwani1330 @KartikKar19 @N3v1 for brainstorming this issue, I highly appreciate the due diligence.
> cc: @AryanGupta0007

@Devansh-Singh-Parmar see this message above from @SID262000

**Comment by Ashwani1330** [comment]
> > Since we have this compatibility issue for the GitHub pages with Django & Python, I request everyone to wait until further notice on the change of the tool stack which will only be possible after we integrate the missing pieces.
> > Many thanks @Ashwani1330 @KartikKar19 @N3v1 for brainstorming this issue, I highly appreciate the due diligence.
> > cc: @AryanGupta0007
> 
> @Devansh-Singh-Parmar see this message above from @SID262000 

I affirmatively agree.

**Comment by N3v1** [comment]
@Devansh-Singh-Parmar We can't create Github Pages 'cause this project uses Django (Python). With Github pages you can only use HTML, CSS and JS

Maybe you can deploy it on Vecel?! I don't know

**Comment by SID262000** [comment]
Everyone please wait for this Issue to be resolved as it'll be based on the decision of changing the tech stack. Everyone is requested to shift their attention to other issues and get it resolved by the end of this week. Many Thanks 🙏
@TeamCodeArena/deliverease

**Comment by Devansh-Singh-Parmar** [comment]
Okay everybody thanks for letting me know!
