### ISSUE TITLE
Add SECURITY.md file

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#5]
Please add a detailed Security file for someone to report any vulnerability. I've already attached a sample in the form of #4

Reference: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by neelansh27** [comment]
I would like to work on this issue, please assign it to me.

**Comment by SID262000** [comment]
Thanks, @neelansh27
Closing this Issue
