### ISSUE TITLE
Update Gitignore

### ISSUE THREAD

**Issue by AryanGupta0007** [TeamCodeArena/DeliverEase#52]
The gitignore file does not contain the some extensions and folders that are auto-generated and of no use so add them to gitignore.

**Comment by N3v1** [comment]
I can work on it on Friday @AryanGupta0007, if you want.
Just tell me which files you don't want in the repo so I can list them in the .gitignore.

Best regards 
NH

**Comment by AryanGupta0007** [comment]
@N3v1  thanks but i am already working on this and it is completed as per me but still you can add more in the file if u see anymore useless files. after i commit my changes

**Comment by N3v1** [comment]
Ok @AryanGupta0007
