### ISSUE TITLE
Restructure Repository

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#6]
To ensure consistency in our Repository Architecture, it's important that we follow a standardized approach based on our tech stack. Based on my observations, Python seems to be used in a few areas. Therefore, I would like to share a reference link that can be helpful for us.
Reference: https://docs.python-guide.org/writing/structure/

**Comment by AryanGupta0007** [comment]
The project is structured as per the django official docs 
https://django-project-skeleton.readthedocs.io/en/latest/structure.html
@SID262000

**Comment by AryanGupta0007** [comment]
@SID262000 i just read the article regarding the repo structure so i concluded there is definitely some work needed to restructure the code as per industry standards. I am sorry for my previous response as it was a judge too soon where i thought the article is only about the file structure

**Comment by neelansh27** [comment]
I would also like to contribute to this issue as well.

**Comment by AryanGupta0007** [comment]
@SID262000  This issue is close worthy as most of the checkpoints specified in the reference as been accomplished!.

**Comment by SID262000** [comment]
Sure thing, @AryanGupta0007. Many Thanks to you and @neelansh27 for working diligently towards getting this issue resolved and improvising our code repository.
