### ISSUE TITLE
Add Missing Documentation/Refactor the front-end codebase

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#7]
It is necessary to document every function and class in accordance with the tech stack and refactor the codebase wherever possible.

**Comment by Devansh-Singh-Parmar** [comment]
please explain more about this

**Comment by AryanGupta0007** [comment]
@Devansh-Singh-Parmar  you have to add the documentation to the front end code. like what a particular html/css/js code does

**Comment by AryanGupta0007** [comment]
refer this article: https://minkovski-d.medium.com/the-path-to-a-useful-and-maintainable-frontend-documentation-80b8b7cbbd26 @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
I need help in this, anyone who want to collaborate?

**Comment by Atrika10** [comment]
I want Devansh @Devansh-Singh-Parmar

**Comment by Devansh-Singh-Parmar** [comment]
Go on @Atrika10

**Comment by N3v1** [comment]
Hi @Devansh-Singh-Parmar,
Hi @Atrika10,
Do you need any help with the documentation? 

Best regards
NH

**Comment by Devansh-Singh-Parmar** [comment]
Hello @N3v1 
Seller doccumentation is done, now I am doing  buyer documentation, it's a bit big work so taking time, Thank you for asking, I'll let you know If needed.

cc @N3v1

**Comment by N3v1** [comment]
Sure @Devansh-Singh-Parmar 
Just mention me if you need help

**Comment by Devansh-Singh-Parmar** [comment]
Sure, why not!
cc @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
Close worth 
Cc @SID262000

**Comment by Atrika10** [comment]
Completed #7
