### ISSUE TITLE
Create Wiki Page

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#72]
Placeholder: https://github.com/TeamCodeArena/DeliverEase/wiki
Reference: https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis

**Comment by N3v1** [comment]
Hi @SID262000 👋,
maybe I could help, if you want

Best regards
NH

**Comment by SID262000** [comment]
Sure @N3v1. Many Thanks

**Comment by N3v1** [comment]
What should be on the Wiki homepage? @SID262000

**Comment by SID262000** [comment]
@N3v1 Just follow any standard repository which is high rated and try putting down a similar one here. Feel free to ask any questions in this thread, Thanks

**Comment by N3v1** [comment]
Hi @SID262000, 
I'm now done with the Wiki, how should I add this to your repo? To see the Wiki just click on [**this link**](https://github.com/N3v1/DeliverEase/wiki).

Best regards
NH

**Comment by SID262000** [comment]
Many Thanks @N3v1 for creating the Wiki. Great work!

We can create a link from the GitHub Pages for enlarged visibility.

Feel free to create a PR for the same, I'll merge it as appropriate.

**Comment by N3v1** [comment]
@SID262000, Should I create a new section in the README.md to link to the wiki in my fork?

**Comment by SID262000** [comment]
For the time being, you can do that. But there should be really a way to reference it from the GitHub pages.
cc: @N3v1

**Comment by Devansh-Singh-Parmar** [comment]
This issue should get closed.

cc @SID262000 @N3v1
