### ISSUE TITLE
Add missing documentation/refactor backend codebase

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#8]
It is necessary to document every function and class in accordance with the tech stack and refactor the codebase wherever possible.

**Comment by AryanGupta0007** [comment]
I would like to work on this issue! Please assign this issue to me!

**Comment by SID262000** [comment]
We will keep the issue open for further improvisation if needed.

**Comment by SID262000** [comment]
@AryanGupta0007 Keep it assigned to yourself until issue is closed

**Comment by AryanGupta0007** [comment]
As i am not working on this issue. I think I should unassign myself so that any one else who wishes to work on this can take up this issue. 
cc: @SID262000

**Comment by SID262000** [comment]
Sure Aryan, feel free to unassign yourself in case you feel so. I was under the assumption that @neelansh27 and you were working on this.

**Comment by neelansh27** [comment]
@SID262000  I've discussed with @AryanGupta0007 , we will be working on this issue together.

**Comment by AryanGupta0007** [comment]
i unassigned myself as currently I  don't have the time for this vast issue.  Maybe give chance to a newcomer so they can atleast make some contribution as docs are the best beginner friendly issues.
cc: @SID262000

**Comment by SID262000** [comment]
Sure thing @AryanGupta0007 . Thanks for the update

**Comment by N3v1** [comment]
Hi @SID262000,
Hi @AryanGupta0007,
Do you need any help with the documentation? If yes, I'll try to help you wherever I can.

**Comment by SID262000** [comment]
@AryanGupta0007 Please confirm.
Thanks @N3v1 for your availability, really appreciate it!

**Comment by AryanGupta0007** [comment]
@SID262000 i am not working on this issue .

**Comment by SID262000** [comment]
@N3v1 Please start contributing to it actively.
Also, @Maghish feel free to join in, to speed up the process.
Thanks @AryanGupta0007 for acknowledging

**Comment by N3v1** [comment]
Hi @SID262000, I would like to start working on it from Friday as I have a very busy week

@Maghish We have to split the work

@SID262000 What should we exactly document? Please provide a task list for us. Thanks

**Comment by SID262000** [comment]
It's really difficult for me to provide a detailed written Todo list for each Issue. That's the very reason, I scheduled a weekly staff meeting.
I might be able to update on the Huddle at max, let me know if that works.
cc: @N3v1 @Maghish

For starting point, please refer to the References attached in the Issue description.

**Comment by Maghish** [comment]
Sorry I can't work on this issue, I am not suitable for this.
Cc: @SID262000 @N3v1

**Comment by neelansh27** [comment]
@N3v1 Thanks for offering help but I think @AryanGupta0007 has already covered most of the documentation part, currently I'm fixing all the pydocstyle (Docstring) errors so I think rather than documentation, it would be better to work on refactoring (if needed).

**Comment by N3v1** [comment]
> @N3v1 Thanks for offering help but I think @AryanGupta0007 has already covered most of the documentation part, currently I'm fixing all the pydocstyle (Docstring) errors so I think rather than documentation, it would be better to work on refactoring (if needed).

I could try it but I don't have experience with Python @neelansh27

**Comment by neelansh27** [comment]
Ok, then If you find anything missing in documentation, feel free to make changes and ask for help wherever needed since you are not familiar with python @N3v1 

In our project, you need to document python files present in main, userAuth, buyer and seller folder.

Go through this [page](https://realpython.com/documenting-python-code/) to see how to document python code. No need to read the whole document, just get the basic idea when to use comments and when to use docstrings and how to declare them.

**Comment by N3v1** [comment]
Thanks @neelansh27

**Comment by SID262000** [comment]
Feel free to close this issue, if done.
cc: @neelansh27

**Comment by neelansh27** [comment]
@SID262000 I don't have the authority to close this issue and @N3v1 might contribute to this issue.
I don't have anything else to add, so it's ok if you unassign this issue to me.

**Comment by AryanGupta0007** [comment]
I think this issue is close worthy
 If @N3v1 is not working on this issue
Cc: @SID262000

**Comment by SID262000** [comment]
@N3v1 please confirm ASAP

**Comment by N3v1** [comment]
@SID262000 I‘m not working on it because the documentation is already done - I think
