### ISSUE TITLE
Add more test cases 

### ISSUE THREAD

**Issue by AryanGupta0007** [TeamCodeArena/DeliverEase#89]
There are files that needed to be added for the Backend.
cc: @SID262000

**Comment by SID262000** [comment]
Many Thanks @AryanGupta0007 for doing the background investigation and figuring out the missing pieces.

**Comment by AryanGupta0007** [comment]
hey @SID262000 i have added all the required test cases . The code coverage report is now at 96%. You can go ahead and merge this.
