### ISSUE TITLE
Add GitHub Hooks

### ISSUE THREAD

**Issue by SID262000** [TeamCodeArena/DeliverEase#9]
We need to add GitHub hooks to ensure the best code only gets pushed to the repository.

Reference: https://medium.com/@f3igao/get-started-with-git-hooks-5a489725c639

**Comment by neelansh27** [comment]
I want to work on this issue and therefore, I request @SID262000 to please assign it to me.

**Comment by SID262000** [comment]
@neelansh27 Make sure to include all the Python linters at least as the pre-commit hook

**Comment by SID262000** [comment]
Great work, @neelansh27, highly appreciate it!
This is a really remarkable achievement on our action item which will definitely help make the codebase clean and refactored.
